version: '3.8'

services:

    # Service - ecommerce-db-server
    ecommerce-db-server:
        container_name: ecommerce-db-server
        image: postgres:10.12
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ecommerce-db
        volumes:
            - /opt/apps/ecommerce/data/ecommerce-db:/var/lib/postgresql/data

# Service - ecommerce-service
    ecommerce-service:
        container_name: ecommerce-service
        image: img/ecommerce-service:1.0.0-SNAPSHOT
        restart: always
        ports:
            - "8098:8098"
        depends_on:
            - ecommerce-db-server

